apply plugin: 'com.android.application'

ext.versionMajor = 1
ext.versionMinor = 3
ext.versionPatch = 2
ext.versionClassifier = null

android {
    compileSdk 33
    defaultConfig {
        applicationId "com.mesalabs.ten.update"
        namespace "com.mesalabs.ten.update"
        minSdk 31
        targetSdk 33
        versionCode generateVersionCode()
        versionName generateVersionName()
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        checkReleaseBuilds false
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
    ndkVersion ndkVersion
}

private Integer generateVersionCode() {
    return ext.versionMajor * 10000 + ext.versionMinor * 100 + ext.versionPatch
}

private String generateVersionName() {
    String versionName = "${ext.versionMajor}.${ext.versionMinor}.${ext.versionPatch}"
    if (ext.versionClassifier != null) {
        versionName += "-" + ext.versionClassifier
    }
    return versionName
}

configurations.all {
    resolutionStrategy {
        force "androidx.core:core:1.10.1"
        force "androidx.core:core-ktx:1.10.1"
        force "androidx.room:room-runtime:2.5.2"
        force "androidx.room:room-compiler:2.5.2"
        force "androidx.sqlite:sqlite:2.3.1"
        force "androidx.sqlite:sqlite-framework:2.3.1"
        force "androidx.annotation:annotation-experimental:1.3.1"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.annotation:annotation:1.1.0"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.1.0'
    implementation "androidx.lifecycle:lifecycle-process:2.2.0"
    implementation 'androidx.preference:preference:1.1.1'
    implementation "androidx.transition:transition:1.3.1"
    implementation "com.google.android.material:material:1.3.0-alpha03"

    implementation "com.github.tonyofrancis.Fetch:fetch2:3.4.1"
    implementation 'com.github.tajchert:WaitingDots:0.6.1'
    implementation 'com.github.tonyofrancis.Fetch:fetch2:3.4.1'

    implementation "androidx.core:core-ktx:1.10.1"
    implementation "androidx.core:core:1.10.1"
    implementation "androidx.sqlite:sqlite:2.3.1"
    implementation "androidx.sqlite:sqlite-framework:2.3.1"
    implementation "androidx.annotation:annotation-experimental:1.3.1"
    implementation "androidx.room:room-runtime:2.5.2"
    annotationProcessor "androidx.room:room-compiler:2.5.2"

    testImplementation 'junit:junit:4.12'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
